address review feedback (part 2)
nabokihms/kubernetes-enhancements pull request #3
Opened 2023-06-02 20:05 UTC by aramase

2023-06-02 20:06 UTC, aramase commented
cc @enj

2023-06-03 00:30 UTC, enj requested changes

2023-06-03 00:30 UTC, enj commented on keps/sig-auth/3331-structured-config-for-oidc-authentication/README.md
> +        // xref: https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/#api-server-to-nodes-pods-and-services
Uh... we would validate the TLS connection as normal - the hostname on the leaf cert would need to match `oidc.oidc-namespace` in this example and be verified by the given CA data.

2023-06-03 00:30 UTC, enj commented on keps/sig-auth/3331-structured-config-for-oidc-authentication/README.md
> +        //     }
```suggestion
        //     "claims": {
        //         "roles":"foo,bar",
        //         "other_roles":"baz,qux"
        //         "is_admin": true
        //     }
```

2023-06-03 00:30 UTC, enj commented on keps/sig-auth/3331-structured-config-for-oidc-authentication/README.md
>          URL string `json:"url,omitempty"`
Document which network proxy is going to be used?

2023-06-03 00:30 UTC, enj commented on keps/sig-auth/3331-structured-config-for-oidc-authentication/README.md
>  ### Flags
For rollback, mention that the if they were using the pre-existing OIDC flags before, that they would need to add those back.

2023-06-06 16:51 UTC, merged